In [ ]:
# Experiment 9 - Study of numpy Library
# Naman Bothra
# PRN - 25070123078

In [ ]:
# why numpy
# faster than list
# used for numercal computation
# Base for pandas

In [3]:
# Declaration of numpy
import numpy as np
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [4]:
# Dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# size of array
print(a.size)
print(b.size)

7
6


In [9]:
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)

(7,)
(2, 3)
int64
int64


In [12]:
# In-Built functions using Numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye((3))


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(b * 2)
print()
print(a + 5)
print()

[[ 2  4  6]
 [ 8 10 12]]

[  6  15  25  35  45  55 505]



In [22]:
print(np.mean(a))
print(np.median(a))


93.0
30.0


In [27]:
print(np.min(a))
print(np.max(a))
print(np.sum(a))

1
500
651
